apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: docu-genius-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: docu-genius
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60  # target 60% CPU usage
