{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: {{ .Values.redis.servicePort }}
      targetPort: {{ .Values.redis.servicePort }}
{{- end }}