from mcp_sdk.tool import BaseTool
import subprocess

class GitTool(BaseTool):
    name = "submit_pull_request"
    description = "Create PR for document change to repo"
    # MCP Tool to Submit PR
    def run(self, repo_path: str, branch: str, commit_msg: str, pr_title: str):
        subprocess.run(["git", "-C", repo_path, "checkout", "-b", branch])
        subprocess.run(["git", "-C", repo_path, "add", "."])
        subprocess.run(["git", "-C", repo_path, "commit", "-m", commit_msg])
        subprocess.run(["git", "-C", repo_path, "push", "-u", "origin", branch])
        subprocess.run([
            "gh", "pr", "create", "--repo", "user/repo", "--head", branch,
            "--title", pr_title, "--body", "Auto-generated by MCP."
        ])
        return "Pull request submitted."
