name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:8.0
        ports:
          - 6379:6379
      milvus:
        image: milvusdb/milvus:v2.6.0
        ports:
          - 19530:19530
          - 9091:9091
        options: >-
          --health-cmd="curl -f http://localhost:9091/healthz || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov flake8

    - name: Lint with flake8
      run: |
        flake8 . --exclude=venv,__pycache__,.venv --max-line-length=100

    - name: Run tests with coverage
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: true
